apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"busybox"},"name":"busybox-deployment","namespace":"default"},"spec":{"replicas":10,"selector":{"matchLabels":{"app":"busybox"}},"template":{"metadata":{"labels":{"app":"busybox"}},"spec":{"containers":[{"args":["sleep","40000"],"image":"busybox","name":"busybox","resources":{"limits":{"cpu":"1","memory":"1Gi"},"requests":{"cpu":"80m","memory":"1Gi"}}}]}}}}
  creationTimestamp: "2020-01-21T00:05:38Z"
  generation: 2
  labels:
    app: busybox
  name: busybox-deployment
  namespace: default
  resourceVersion: "4249442"
  selfLink: /apis/apps/v1/namespaces/default/deployments/busybox-deployment
  uid: 8ced390a-c45c-4325-b9ff-2980456a7f47
spec:
  progressDeadlineSeconds: 600
  replicas: 30
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: busybox
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: busybox
    spec:
      containers:
      - args:
        - sleep
        - "40000"
        image: busybox
        imagePullPolicy: Always
        name: busybox
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 80m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 30
  conditions:
  - lastTransitionTime: "2020-01-21T00:05:38Z"
    lastUpdateTime: "2020-01-21T00:07:41Z"
    message: ReplicaSet "busybox-deployment-58769f7458" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-01-21T00:37:57Z"
    lastUpdateTime: "2020-01-21T00:37:57Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 30
  replicas: 30
  updatedReplicas: 30
